[Distribution]
Distribution=ubuntu
Release=resolute
Repositories=deb http://archive.ubuntu.com/ubuntu/ resolute universe

[Build]
WithNetwork=no
ToolsTree=default

[Output]
Format=tar
CompressOutput=xz
ImageId=philosophers

[Validation]
Checksum=yes

[Content]
Packages=libpam-systemd
         systemd
         systemd-sysv
         udev
         dbus
         dma
         mailutils
         finger
         inotify-tools
         iproute2
         locales
         neovim
         man-db
RemoveFiles=/etc/update-motd.d/50-motd-news,/etc/legal
