#!/bin/sh
if [ "$#" -lt 2 ]
then
	echo "Usage: ${0##*/} name 'Full Name' ['Comment' [project_file]]" >&2
	exit 64
fi
set -e
umask 022
getent group philosophers > /dev/null || addgroup --firstgid 1500 philosophers
adduser --disabled-password --shell /bin/bash --gecos "$2,,,,$3" "$1" 
adduser "$1" philosophers
mkdir -p /home/"$1"/.config/systemd/user/default.target.wants
ln -sf /usr/lib/systemd/user/*.path /home/"$1"/.config/systemd/user/default.target.wants
loginctl enable-linger "$1"
if [ -z "$4" ]
then
    exit 0
fi
if [ -e "$4" ]
then
    chmod 0751 "/home/$1"
    install -o "$1" -g "$1" -m 0644 -T "$4" "/home/$1/.project"
fi
